crds:
  enabled: true
  keep: true
prometheus:
  enabled: true
webhook:
  timeoutSeconds: 4
enableCertificateOwnerRef: true
extraArgs:
  - "--dns01-recursive-nameservers-only"
  - "--dns01-recursive-nameservers=1.1.1.1:53"
