providers:
  kubernetesCRD:
    allowCrossNamespace: true
ingress:
  ingressClass:
    enabled: false
    isDefaultClass: true
    name: traefik
deployment:
  replicas: 3
  podLabels:
    app: traefik
nodeSelector:
  nodepool: worker
service:
  spec:
    externalTrafficPolicy: Local
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: "DoNotSchedule"
    labelSelector:
      matchLabels:
        app: traefik
additionalArguments:
  - "--entryPoints.ssh.address=:22/tcp"
  - "--entryPoints.minecraft-gtnh.address=:25566/tcp"
  - "--entryPoints.minecraft-tfg.address=:25567/tcp"
  - "--entryPoints.minecraft-star-technology.address=:25568/tcp"
ports:
  ssh:
    name: ssh
    port: 22
    exposedPort: 22
    expose:
      default: true
    protocol: TCP
  minecraft-gtnh:
    name: minecraft-gtnh
    port: 25566
    exposedPort: 25566
    expose:
      default: true
    protocol: TCP
  minecraft-tfg:
    name: minecraft-tfg
    port: 25567
    exposedPort: 25567
    expose:
      default: true
    protocol: TCP
  minecraft-star-technology:
    name: minecraft-star-technology
    port: 25568
    exposedPort: 25568
    expose:
      default: true
    protocol: TCP
