image:
  tag: "v3.6.4"
providers:
  kubernetesCRD:
    allowCrossNamespace: true
ingress:
  ingressClass:
    enabled: false
    isDefaultClass: true
    name: traefik
deployment:
  replicas: 1
  podLabels:
    app: traefik
nodeSelector:
  nodepool: worker
service:
  spec:
    externalTrafficPolicy: Local
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: "DoNotSchedule"
    labelSelector:
      matchLabels:
        app: traefik
additionalArguments:
  - "--entryPoints.ssh.address=:2222/tcp"
ports:
  ssh:
    port: 2222
    exposedPort: 2222
    expose:
      default: true
    protocol: TCP
