providers:
  kubernetesCRD:
    allowCrossNamespace: true
ingress:
  ingressClass:
    enabled: true
    isDefaultClass: true
    name: traefik
deployment:
  replicas: 3
  podLabels:
    app: traefik
nodeSelector:
  nodepool: worker
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: "ScheduleAnyway"
    labelSelector:
      matchLabels:
        app: traefik
additionalArguments:
  - "--entryPoints.ssh.address=:22/tcp"
ports:
  ssh:
    name: ssh
    port: 22
    exposedPort: 22
    expose:
      default: true
    protocol: TCP
