global:
  security:
    allowInsecureImages: true # needed for ghcr.io images
image:
  registry: docker.io
  repository: bitnamilegacy/external-dns
  tag: 0.18.0-debian-12-r1
  pullPolicy: IfNotPresent
interval: 10s
provider: pihole
policy: upsert-only
txtOwnerId: "homelab"
pihole:
  server: http://rashid
nodeSelector:
  nodepool: worker
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-admin
        key: app-password
extraArgs:
  pihole-api-version: 6
serviceAccount:
  create: true
  name: "external-dns"
ingressClassFilters:
  - nginx-internal
metrics:
  enabled: false
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    selector:
      matchLabels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/instance: externaldns-pihole
    port: 7979
