interval: 10s
provider: pihole
policy: upsert-only
txtOwnerId: "homelab"
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-admin
        key: password
serviceAccount:
  create: true
  name: "external-dns"
ingressClassFilters:
  - nginx-internal
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    selector:
      matchLabels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/instance: externaldns-pihole
    port: 7979
