service:
  http:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: git.dogar.dev
      metallb.universe.tf/allow-shared-ip: gitea
  ssh:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: git.dogar.dev
      metallb.universe.tf/allow-shared-ip: gitea
ingress:
  enabled: true
  className: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
  hosts:
    - host: git.dogar.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-tls
      hosts:
        - git.dogar.dev
gitea:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6060"
  admin:
    existingSecret: gitea-admin
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  config:
    server:
      ENABLE_PPROF: true
      ENABLE_GZIP: true
      LFS_START_SERVER: true
    database:
      DB_TYPE: postgres
      HOST: postgres-cluster-rw.postgres-system.svc.cluster.local:5432
      NAME: giteadb
      USER: gitea
    cache:
      ADAPTER: memcache
      HOST: memcached.memcached-system.svc.cluster.local:11211
    session:
      PROVIDER: db
      PROVIDER_CONFIG: ""
    lfs:
      STORAGE_TYPE: local
    service:
      DISABLE_REGISTRATION: true
  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea-postgres
          key: password
persistence:
  enabled: true
  accessModes:
    - ReadWriteMany
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
