containerSecurityContext:
  readOnlyRootFilesystem: false
service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: memcached.dogar.dev
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 10s
    scrapeTimeout: 10s
