tenant:
  name: minio-homelab
  configuration:
    name: minio-homelab
  pools:
    - name: minio-homelab
      servers: 3
      volumesPerServer: 2
      storageClassName: longhorn-crypto
  exposeServices:
    minio: true
    prometheusOperator: true
ingress:
  api:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-issuer
      cert-manager.io/acme-challenge-type: dns01
      cert-manager.io/private-key-size: "4096"
    host: minio.dogar.dev
    tls:
      - secretName: minio-tls
        hosts:
          - minio.dogar.dev
  console:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-issuer
      cert-manager.io/acme-challenge-type: dns01
      cert-manager.io/private-key-size: "4096"
    host: minio-console.dogar.dev
    tls:
      - secretName: minio-console-tls
        hosts:
          - minio-console.dogar.dev
