controller:
  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
    parameters: {}
  ingressClass: nginx-internal
tcp:
  22:       "homelab/gitea-ssh:22"
  25565:    "minecraft/monifactory-server:25565"
