controller:
  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
    parameters: {}
  ingressClass: nginx-internal
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: postgres.home
tcp:
  5432: "postgres-system/postgres-cluster-rw:5432"
  2222: "gitea-system/gitea-ssh:22"
