---
DNS1:
  192.168.0.1
DNS2:
  1.1.1.1
admin:
  enabled: true
  existingSecret: pihole-admin
  passwordKey: password
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  hosts:
    - pihole.home
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.home
serviceWeb:
  loadBalancerIP: 192.168.0.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.0.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9617"
monitoring:
  sidecar:
    enabled: true
    port: 9617
    image:
      repository: ekofr/pihole-exporter
      tag: v0.3.0
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
