---
DNS1:
  1.1.1.1
DNS2:
  1.0.0.1
admin:
  enabled: true
  existingSecret: pihole-admin
  passwordKey: password
persistentVolumeClaim:
  enabled: true
  storageClass: longhorn
  size: 10Gi
  accessModes:
    - ReadWriteMany
ingress:
  enabled: true
  ingressClassName: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/private-key-size: "4096"
  hosts:
    - pihole.dogar.dev
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.dogar.dev
serviceWeb:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: ClusterIP
  https:
    enabled: false
serviceDns:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  loadBalancerIP: 192.168.18.250
serviceDhcp:
  enabled: false
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
dnsmasq:
  staticDhcpEntries:
    - dhcp-host=B0:41:6F:0F:A8:D3,192.168.18.10,homelab-0
    - dhcp-host=B0:41:6F:0F:AE:89,192.168.18.11,homelab-1
    - dhcp-host=B0:41:6F:0F:A0:CD,192.168.18.12,homelab-2
hostNetwork: true
hostname: pihole
capabilities:
  add:
    - NET_ADMIN
extraEnvVars:
  TZ: "Asia/Karachi"
  DNSSEC: "true"
  FTLCONF_LOCAL_IPV4: "192.168.18.250"
  INTERFACE: "enp1s0"
  DNSMASQ_LISTENING: "single"
  DHCP_ACTIVE: "true"
  DHCP_START: "192.168.18.2"
  DHCP_END: "192.168.18.20"
  DHCP_ROUTER: "192.168.18.1"
  PIHOLE_DOMAIN: "pihole.dogar.dev"
  VIRTUAL_HOST: "pihole.dogar.dev"
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9617"
monitoring:
  sidecar:
    enabled: true
    port: 9617
    image:
      repository: ekofr/pihole-exporter
      tag: v0.3.0
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
