grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer
    hosts:
      - grafana.home
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.home
