grafana:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: grafana.dogar.dev
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-issuer
      cert-manager.io/private-key-algorithm: ED25519
      cert-manager.io/acme-challenge-type: dns01
    hosts:
      - grafana.dogar.dev
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.dogar.dev
