architecture: standalone

auth:
  enabled: true
  sentinel: true
  existingSecret: redis
  existingSecretPasswordKey: password

master:
  persistence:
    enabled: false
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: redis.dogar.dev

replica:
  replicaCount: 0
  persistence:
    enabled: false

sentinel:
  enabled: false
