ingress:
  enabled: true
  ingressClassName: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/private-key-size: "4096"
  hosts:
    - host: docs.rihla.digital
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: docs-rihla-digital
      hosts:
        - docs.rihla.digital

postgresql:
  enabled: false
  postgresqlDatabase: docs
  postgresqlUser: docs
  postgresqlHost: postgres-cluster-rw.postgres-system.svc.cluster.local
  postgresqlPort: 5432
  existingSecret: docs-postgres
  existingSecretKey: password
