---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-cert
  namespace: elastic-system
spec:
  secretName: elasticsearch-cert
  privateKey:
    algorithm: ECDSA
    size: 384
  usages:
    - server auth
  dnsNames:
    - elastic.dogar.dev
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.15.2
  http:
    service:
      metadata:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: elastic.dogar.dev
    tls:
      certificate:
        secretName: elasticsearch-cert
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: ["master", "data"]
