---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.15.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      certificate:
        secretName: kibana-kb-http-tls-internal
  config:
    server.publicBaseUrl: "https://kibana.dogar.dev"
    xpack.security.authc.providers:
      oidc.authentik:
        order: 0
        realm: authentik
        description: "Log in with Authentik"
      basic.basic1:
        order: 1
