global:
  nodeSelector:
    nodepool: worker
defaultSettings:
  defaultReplicaCount: "1"
  storageOverProvisioningPercentage: "100"
  backupCompressionMethod: "gzip"
  replicaSoftAntiAffinity: "true"
  concurrentReplicaRebuildPerNodeLimit: "1"
  replicaReplenishmentWaitInterval: "600"
  disableSchdedulingOnCordonedNode: "true"
defaultBackupStore:
  backupTarget: "s3://shahab-longhorn-backups@sgp1/"
  backupTargetCredentialSecret: digital-ocean-spaces
  pollInterval: "3600"
metrics:
  serviceMonitor:
    enabled: true
ingress:
  enabled: false
persistence:
  reclaimPolicy: Retain
