kubeProxyReplacement: true
cluster:
  name: omf
  id: 1
cni:
  chainingMode: none
routingMode: tunnel
ipam:
  mode: kubernetes
bpf:
  masquerade: true
dnsProxy:
  enableTransparentMode: false
resources:
  requests:
    memory: 128Mi
