storage: /verdaccio/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@*/*":
    access: $all
    publish: never
    proxy: npmjs

  "**":
    access: $all
    publish: never
    proxy: npmjs

log:
  - {type: stdout, format: pretty, level: http}
