---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-domains-config
  namespace: homelab
data:
  DOMAINS: "auth.dogar.dev,grafana.dogar.dev"
  PROXIED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-domains-config-non-proxied
  namespace: homelab
data:
  DOMAINS: "dogar.dev,git.dogar.dev"
  PROXIED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - name: cloudflare-ddns
        image: favonia/cloudflare-ddns:latest
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: token
        - name: DOMAINS
          valueFrom:
            configMapKeyRef:
              name: cloudflare-domains-config
              key: DOMAINS
        - name: UPDATE_TIMEOUT
          value: "30s"
        - name: IP6_PROVIDER
          value: "none"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns-non-proxied
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - name: cloudflare-ddns-non-proxied
        image: favonia/cloudflare-ddns:latest
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: token
        - name: DOMAINS
          valueFrom:
            configMapKeyRef:
              name: cloudflare-domains-config-non-proxied
              key: DOMAINS
        - name: UPDATE_TIMEOUT
          value: "30s"
        - name: IP6_PROVIDER
          value: "none"
