---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monifactory-data
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gtnh-data
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modpacks
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
