---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monifactory-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gtnh-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfg-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atm10-data
  namespace: minecraft
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/backup: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
