---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: curseforge
  namespace: minecraft
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Lab/items/curseforge"
