---
apiVersion: v1
kind: Service
metadata:
  name: monifactory-server
  namespace: minecraft
  labels:
    app: monifactory-server
spec:
  type: ClusterIP
  ports:
    - name: monifactory
      port: 25565
  selector:
    app: monifactory-server
---
apiVersion: v1
kind: Service
metadata:
  name: gtnh-server
  namespace: minecraft
  labels:
    app: gtnh-server
spec:
  type: ClusterIP
  ports:
    - name: gtnh
      port: 25565
  selector:
    app: gtnh-server
---
apiVersion: v1
kind: Service
metadata:
  name: atm10-server
  namespace: minecraft
  labels:
    app: atm10-server
spec:
  type: ClusterIP
  ports:
    - name: atm10
      port: 25565
  selector:
    app: atm10-server
---
apiVersion: v1
kind: Service
metadata:
  name: star-technology-server
  namespace: minecraft
  labels:
    app: star-technology-server
spec:
  type: ClusterIP
  ports:
    - name: star-technology
      port: 25565
  selector:
    app: star-technology-server
