---
apiVersion: v1
kind: Service
metadata:
  name: monifactory-server
  namespace: minecraft
  labels:
    app: monifactory-server
spec:
  type: ClusterIP
  ports:
    - name: monifactory
      port: 25565
  selector:
    app: monifactory-server
---
apiVersion: v1
kind: Service
metadata:
  name: gtnh-server
  namespace: minecraft
  labels:
    app: gtnh-server
spec:
  type: ClusterIP
  ports:
    - name: gtnh
      port: 25565
  selector:
    app: gtnh-server
