---
apiVersion: v1
kind: Service
metadata:
  name: monifactory-server
  namespace: minecraft
  labels:
    app: monifactory-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dogar.dev
spec:
  type: ClusterIP
  ports:
    - name: monifactory
      port: 25565
  selector:
    app: monifactory-server
