---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monifactory-server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: monifactory-server
  template:
    metadata:
      labels:
        app: monifactory-server
    spec:
      containers:
        - name: monifactory-server
          image: itzg/minecraft-server:java17
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: DIFFICULTY
              value: "peaceful"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              value: "$2a$10$12Z0ZWRDkHKShnN2gdZdY./Cj8BjpzIdcwuFXx9HrPsPUH90vwHcK"
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/monifactory/"
            - name: VERSION
              value: "1.20.1"
            - name: INIT_MEMORY
              value: 4G
            - name: MAX_MEMORY
              value: 8G
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: USE_MEOWICE_FLAGS
              value: "TRUE"
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 4
              memory: "4Gi"
            limits:
              cpu: 8
              memory: "8Gi"
          readinessProbe:
              exec:
                command:
                - mc-health
              initialDelaySeconds: 30
              periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - mc-health
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
          - name: monifactory-data
            mountPath: /data
          - name: modpacks
            mountPath: /modpacks
      volumes:
        - name: monifactory-data
          persistentVolumeClaim:
            claimName: monifactory-data
        - name: modpacks
          persistentVolumeClaim:
            claimName: modpacks
