---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monifactory-server
  namespace: minecraft
spec:
  serviceName: monifactory-server
  selector:
    matchLabels:
      app: monifactory-server
  template:
    metadata:
      labels:
        app: monifactory-server
    spec:
      nodeSelector:
        nodepool: worker
      containers:
        - name: monifactory-server
          image: itzg/minecraft-server:java17
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: DIFFICULTY
              value: "peaceful"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge
                  key: credential
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/monifactory/"
            - name: VERSION
              value: "1.20.1"
            - name: INIT_MEMORY
              value: 4G
            - name: MAX_MEMORY
              value: 12G
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: USE_MEOWICE_FLAGS
              value: "TRUE"
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 4
              memory: "4Gi"
            limits:
              cpu: 8
              memory: "12Gi"
          volumeMounts:
          - name: monifactory-data
            mountPath: /data
      volumes:
        - name: monifactory-data
          persistentVolumeClaim:
            claimName: monifactory-data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gtnh-server
  namespace: minecraft
spec:
  serviceName: gtnh-server
  selector:
    matchLabels:
      app: gtnh-server
  template:
    metadata:
      labels:
        app: gtnh-server
    spec:
      nodeSelector:
        nodepool: worker
      containers:
        - name: gtnh-server
          image: itzg/minecraft-server:java25
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: DIFFICULTY
              value: "peaceful"
            - name: TYPE
              value: "CUSTOM"
            - name: GENERIC_PACKS
              value: "GT_New_Horizons_2.8.0_Server_Java_17-25"
            - name: GENERIC_PACKS_SUFFIX
              value: ".zip"
            - name: GENERIC_PACKS_PREFIX
              value: "https://downloads.gtnewhorizons.com/ServerPacks/"
            - name: SKIP_GENERIC_PACK_UPDATE_CHECK
              value: "true"
            - name: MEMORY
              value: 12G
            - name: JVM_OPTS
              value: "-Dfml.readTimeout=180 -Dfml.queryResult=confirm @java9args.txt"
            - name: CUSTOM_JAR_EXEC
              value: "-jar lwjgl3ify-forgePatches.jar nogui"
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
          ports:
            - name: gtnh
              containerPort: 25565
          resources:
            limits:
              cpu: 8
              memory: "12Gi"
          volumeMounts:
          - name: gtnh-data
            mountPath: /data
      volumes:
        - name: gtnh-data
          persistentVolumeClaim:
            claimName: gtnh-data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tfg-server
  namespace: minecraft
spec:
  serviceName: tfg-server
  selector:
    matchLabels:
      app: tfg-server
  template:
    metadata:
      labels:
        app: tfg-server
    spec:
      nodeSelector:
        nodepool: worker
      containers:
        - name: tfg-server
          image: itzg/minecraft-server:java17
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge
                  key: credential
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/terrafirmagreg-modern/"
            - name: CF_FILENAME_MATCHER
              value: "0.10.17"
            - name: VERSION
              value: "1.20.1"
            - name: INIT_MEMORY
              value: 2G
            - name: MAX_MEMORY
              value: 12G
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: USE_MEOWICE_FLAGS
              value: "TRUE"
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 2
              memory: "2Gi"
            limits:
              cpu: 6
              memory: "12Gi"
          volumeMounts:
          - name: tfg-data
            mountPath: /data
      volumes:
        - name: tfg-data
          persistentVolumeClaim:
            claimName: tfg-data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atm10-server
  namespace: minecraft
spec:
  serviceName: atm10-server
  selector:
    matchLabels:
      app: atm10-server
  template:
    metadata:
      labels:
        app: atm10-server
    spec:
      nodeSelector:
        nodepool: worker
      containers:
        - name: atm10-server
          image: itzg/minecraft-server:java21
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge
                  key: credential
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/7121777"
            - name: VERSION
              value: "1.21.1"
            - name: INIT_MEMORY
              value: 2G
            - name: MAX_MEMORY
              value: 15G
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: USE_MEOWICE_FLAGS
              value: "TRUE"
            - name: CF_OVERRIDES_EXCLUSIONS
              value: |
                # Not applicable for server side
                shaderpacks/**
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 2
              memory: "2Gi"
            limits:
              cpu: 6
              memory: "16Gi"
          volumeMounts:
          - name: atm10-data
            mountPath: /data
      volumes:
        - name: atm10-data
          persistentVolumeClaim:
            claimName: atm10-data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: star-technology-server
  namespace: minecraft
spec:
  serviceName: star-technology-server
  selector:
    matchLabels:
      app: star-technology-server
  template:
    metadata:
      labels:
        app: star-technology-server
    spec:
      nodeSelector:
        nodepool: worker
      containers:
        - name: star-technology-server
          image: itzg/minecraft-server:java21
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge
                  key: credential
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/star-technology"
            - name: VERSION
              value: "1.20.1"
            - name: INIT_MEMORY
              value: 2G
            - name: MAX_MEMORY
              value: 15G
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: USE_MEOWICE_FLAGS
              value: "TRUE"
            - name: CF_OVERRIDES_EXCLUSIONS
              value: |
                # Not applicable for server side
                shaderpacks/**
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 2
              memory: "2Gi"
            limits:
              cpu: 6
              memory: "16Gi"
          volumeMounts:
          - name: star-technology-data
            mountPath: /data
      volumes:
        - name: star-technology-data
          persistentVolumeClaim:
            claimName: star-technology-data
