---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atm10-server
  namespace: minecraft
spec:
  serviceName: atm10-server
  selector:
    matchLabels:
      app: atm10-server
  template:
    metadata:
      labels:
        app: atm10-server
    spec:
      nodeSelector:
        nodepool: worker
      containers:
        - name: atm10-server
          image: itzg/minecraft-server:java21
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: MODPACK_PLATFORM
              value: "AUTO_CURSEFORGE"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge
                  key: credential
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/7121777"
            - name: VERSION
              value: "1.21.1"
            - name: INIT_MEMORY
              value: 2G
            - name: MAX_MEMORY
              value: 15G
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: ENABLE_ROLLING_LOGS
              value: "TRUE"
            - name: USE_MEOWICE_FLAGS
              value: "TRUE"
            - name: CF_OVERRIDES_EXCLUSIONS
              value: |
                # Not applicable for server side
                shaderpacks/**
          ports:
            - name: minecraft
              containerPort: 25565
          resources:
            requests:
              cpu: 2
              memory: "2Gi"
            limits:
              cpu: 6
              memory: "16Gi"
          volumeMounts:
          - name: atm10-data
            mountPath: /data
      volumes:
        - name: atm10-data
          persistentVolumeClaim:
            claimName: atm10-data
