replicaCount: 1
image:
  runAsNonRoot: true
nodeSelector:
  nodepool: worker
strategy:
  type: Recreate
storage:
  type: minio
  minio:
    endpoint: "rustfs-tenant-io.homelab.svc.cluster.local:9000"
    bucket: "go-cache"
extraVolumes:
  - name: rustfs-ca
    configMap:
      name: rustfs-ca
extraVolumeMounts:
  - name: rustfs-ca
    mountPath: /etc/ssl/certs/rustfs-ca.crt
    subPath: ca.crt
configEnvVars:
  - name: ATHENS_DOWNLOAD_MODE
    value: "sync"
  - name: ATHENS_GLOBAL_ENDPOINT
    value: "https://proxy.golang.org"
  - name: ATHENS_PROTOCOL_WORKERS
    value: "12"
  - name: ATHENS_MINIO_USE_SSL
    value: "true"
  - name: ATHENS_MINIO_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: rustfs-credentials
        key: accesskey
  - name: ATHENS_MINIO_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: rustfs-credentials
        key: secretkey
  - name: SSL_CERT_FILE
    value: /etc/ssl/certs/rustfs-ca.crt
upstreamProxy:
  enabled: false
