repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: postgres
    url: https://cloudnative-pg.github.io/charts
  - name: gitea
    url: https://dl.gitea.com/charts
  - name: jetstack
    url: https://charts.jetstack.io
---
releases:
  # Distributed Storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.0

  # Load Balancer
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.8

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.values.yaml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - ./values/nginx-internal.values.yaml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.3.4
    values:
      - ./values/externaldns.values.yaml

  # Postgres operator
  - name: postgres-system
    namespace: postgres-system
    chart: cnpg/cloudnative-pg
    version: 0.21.6

  # Memcached
  - name: memcached
    namespace: memcached-system
    chart: bitnami/memcached
    version: 7.4.11

  # Gitea
  - name: gitea
    namespace: gitea-system
    chart: gitea/gitea
    version: 10.4.0
    values:
      - ./values/gitea.values.yaml

  # Cert Manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.3
    values:
      - ./values/cert-manager.values.yaml
