apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-system
spec:
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 2
  primaryUpdateStrategy: unsupervised

  postgresql:
    pg_hba:
      - host all all all md5

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-password

  bootstrap:
    initdb:
      database: postgres
      secret:
        name: postgres-password

  storage:
    size: 1Gi
