---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-system
spec:
  instances: 3
  maxSyncReplicas: 0
  primaryUpdateStrategy: unsupervised
  certificates:
    serverCASecret: postgres-server-cert
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-cert
    replicationTLSSecret: postgres-client-cert
  postgresql:
    pg_hba:
      - hostssl all      shahab   all          cert
      - hostssl sameuser all      all          cert
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: postgres
      secret:
        name: postgres-password
      postInitSQL:
        - 'CREATE USER shahab SUPERUSER;'
  storage:
    size: 10Gi
    storageClass: longhorn-crypto
  walStorage:
    size: 10Gi
    storageClass: longhorn-crypto
