---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-password
  namespace: postgres-system
spec:
  itemPath: "vaults/Lab/items/Postgres"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-system
spec:
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 2
  primaryUpdateStrategy: unsupervised

  postgresql:
    pg_hba:
      - host all all all md5

  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: postgres
      secret:
        name: postgres-password

  storage:
    size: 1Gi
